Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2021-12, with the labels that each got.

#107 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, size/XS, lgtm

#106 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/S, lgtm

#103 Document maturity levels in sandbox
  README.adoc
Labels: cla: yes, approved, size/XS, lgtm

#108 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/S, lgtm

#109 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/S, lgtm

#110 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/S, lgtm

#111 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm
