Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2021-09, with the labels that each got.

#45 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/S, lgtm

#46 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, size/XS, lgtm

#43 Add bind command for creating KameletBindings
  go.mod
  internal/client/client_mock.go
  internal/command/bind.go
  internal/command/bind_test.go
  internal/command/describe_type.go
  internal/command/describe_type_test.go
  internal/command/helpers_test.go
  internal/command/list_types.go
  internal/command/list_types_test.go
  internal/command/types.go
  internal/command/util.go
  internal/root/root.go
  vendor/modules.txt
Labels: cla: yes, size/XL, approved, lgtm

#47 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/eventing/v1/client_mock.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1alpha1/client.go
  vendor/knative.dev/client/pkg/serving/v1alpha1/client_mock.go
  vendor/knative.dev/client/pkg/sources/v1/container_client.go
  vendor/knative.dev/client/pkg/sources/v1/container_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1beta2/ping_client.go
  vendor/knative.dev/client/pkg/sources/v1beta2/ping_client_mock.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: cla: yes, size/XL, approved, lgtm

#49 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#60 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/S, lgtm

#61 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, size/S, lgtm

#58 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#62 Rename list-types and describe-type to "list" and "describe"
  .gitignore
  internal/command/describe.go
  internal/command/describe_test.go
  internal/command/list.go
  internal/command/list_test.go
  internal/root/root.go
Labels: cla: yes, size/L, approved, lgtm

#65 Removed unnecessary go-mod overwrite
  go.mod
  go.sum
  vendor/github.com/go-openapi/spec/.golangci.yml
  vendor/github.com/go-openapi/spec/.travis.yml
  vendor/github.com/go-openapi/spec/README.md
  vendor/github.com/go-openapi/spec/appveyor.yml
  vendor/github.com/go-openapi/spec/bindata.go
  vendor/github.com/go-openapi/spec/cache.go
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/errors.go
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/go.mod
  vendor/github.com/go-openapi/spec/go.sum
  vendor/github.com/go-openapi/spec/header.go
  vendor/github.com/go-openapi/spec/items.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/spec/normalizer.go
  vendor/github.com/go-openapi/spec/operation.go
  vendor/github.com/go-openapi/spec/parameter.go
  vendor/github.com/go-openapi/spec/properties.go
  vendor/github.com/go-openapi/spec/ref.go
  vendor/github.com/go-openapi/spec/resolver.go
  vendor/github.com/go-openapi/spec/response.go
  vendor/github.com/go-openapi/spec/schema.go
  vendor/github.com/go-openapi/spec/schema_loader.go
  vendor/github.com/go-openapi/spec/security_scheme.go
  vendor/github.com/go-openapi/spec/spec.go
  vendor/github.com/go-openapi/spec/validations.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL

#66 Print detailed information of all properties on source kamelet describe
  internal/command/describe.go
  internal/command/describe_test.go
Labels: cla: yes, approved, size/M, lgtm

#63 Add binding list command
  internal/client/client_mock.go
  internal/command/binding.go
  internal/command/binding_create.go
  internal/command/binding_create_test.go
  internal/command/binding_list.go
  internal/command/binding_list_test.go
  internal/command/helpers_test.go
Labels: cla: yes, size/XL, approved, lgtm

#68 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#67 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, size/XS, lgtm

#69 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#72 Fix provider annotation and add support level for describe command
  internal/command/describe.go
  internal/command/describe_test.go
  internal/command/helpers_test.go
  internal/command/types.go
  internal/command/util.go
Labels: cla: yes, approved, size/M, lgtm

#74 Update GVK for read operations + some minor fixes:
  go.mod
  hack/build.sh
  hack/release.sh
  internal/command/bind.go
  internal/command/binding_create.go
  internal/command/binding_list.go
  internal/command/describe.go
  internal/command/describe_test.go
  internal/command/list.go
  internal/command/util.go
  internal/command/util_test.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm

#71 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: cla: yes, approved, size/S, lgtm

#75 build.sh: Cross-build fix + enable linter
  hack/build.sh
  hack/global_vars.sh
  internal/command/list.go
  internal/command/util.go
  internal/command/util_test.go
Labels: cla: yes, approved, size/M, lgtm

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/messaging/v1/channels_client.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/client/pkg/util/unstructured.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm

#77 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, size/S, lgtm

#78 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/client/pkg/kn/flags/podspec_helper.go
  vendor/knative.dev/client/pkg/util/parsing_helper.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#79 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, size/XS, lgtm
