Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2021-03, with the labels that each got.

#5 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, lgtm, size/XS

#6 Update CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#9 Use list-types command
  internal/command/list_types.go
  internal/command/list_types_test.go
  internal/root/root.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#13 [Automated] Fix misspellings
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#11 [Automated] Format markdown
  hack/README.md
Labels: approved, cla: yes, lgtm, size/S

#12 [Automated] Format Go code
  internal/client/client_mock.go
  internal/command/list_types.go
  internal/command/list_types_test.go
  internal/command/types.go
  internal/root/root.go
Labels: approved, cla: yes, lgtm, size/S

#15 Fix scripts exec permissions
  hack/release.sh
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#16 Add license file
  LICENSE
Labels: approved, cla: yes, lgtm, size/L

#14 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#18 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/commands/flags/sink.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#21 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#22 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/dynamic/client.go
  vendor/knative.dev/client/pkg/dynamic/client_mock.go
  vendor/knative.dev/client/pkg/eventing/v1beta1/client.go
  vendor/knative.dev/client/pkg/eventing/v1beta1/client_mock.go
  vendor/knative.dev/client/pkg/kn/commands/flags/sink.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/channels_client.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/channels_client_mock.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/subscriptions_client.go
  vendor/knative.dev/client/pkg/messaging/v1beta1/subscriptions_client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/apply.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1/client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/gitops.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/apiserver_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/apiserver_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/binding_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/binding_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/container_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/container_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/ping_client.go
  vendor/knative.dev/client/pkg/sources/v1alpha2/ping_client_mock.go
  vendor/knative.dev/client/pkg/wait/poll_watcher.go
  vendor/knative.dev/client/pkg/wait/wait_for_ready.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL
