Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2021-10, with the labels that each got.

#82 chore: Update README
  README.adoc
Labels: cla: yes, approved, size/M, lgtm

#80 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/S, lgtm

#84 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/config/defaults.go
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1alpha1/client.go
  vendor/knative.dev/client/pkg/sources/v1/container_client.go
  vendor/knative.dev/client/pkg/sources/v1beta2/ping_client.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm

#85 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/fake/fake.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/signals/signal_posix.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/unstructured/unstructured.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm
