Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2021-04, with the labels that each got.

#24 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/wait/poll_watcher.go
  vendor/knative.dev/client/pkg/wait/wait_for_ready.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#20 Describe Kamelet command
  go.mod
  hack/build.sh
  internal/client/client_mock.go
  internal/command/describe_type.go
  internal/command/describe_type_test.go
  internal/command/helpers_test.go
  internal/command/list_types.go
  internal/command/list_types_test.go
  internal/root/root.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/controller/OWNERS
  vendor/knative.dev/pkg/hash/OWNERS
  vendor/knative.dev/pkg/injection/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/logging/OWNERS
  vendor/knative.dev/pkg/metrics/OWNERS
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/pkg/reconciler/OWNERS
  vendor/knative.dev/pkg/resolver/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XXL

#26 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L
