Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2022-09, with the labels that each got.

#171 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#172 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#170 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/serving/config_changes.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#173 Bump Go version to 1.18
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#176 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#177 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
