Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2022-02, with the labels that each got.

#125 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#127 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#124 [main] Update actions
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
Labels: approved, size/M, lgtm

#126 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#118 fix(#56): Implement source kamelet binding delete
  README.adoc
  internal/client/client_mock.go
  internal/command/bind.go
  internal/command/bind_test.go
  internal/command/binding.go
  internal/command/binding_create.go
  internal/command/binding_create_test.go
  internal/command/binding_delete.go
  internal/command/binding_delete_test.go
  internal/command/describe.go
  internal/command/describe_test.go
Labels: size/L, approved, kind/enhancement, lgtm
