Repository knative-extensions/kn-plugin-source-kamelet, pull requests merged in 2022-04, with the labels that each got.

#132 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#137 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#138 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#136 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/XL, approved, lgtm

#135 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, size/XS, lgtm

#142 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, size/M, lgtm
